workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    environment:
      vars:
        JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
        ANDROID_SDK_ROOT: $HOME/Android/sdk
      groups:
        - production
    triggering:
      events:
        - push
      cancel_previous_builds: true
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web bundle
        script: |
          npm run build
      - name: Sync Capacitor
        script: |
          npx cap sync android
      - name: Build Android
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - tamimiqbalacademic@gmail.com
        notify:
          success: true
          failure: true
