workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    environment:
      vars:
        ANDROID_SDK_ROOT: $HOME/Library/Android/sdk
        VITE_BASE_URL: https://study-sync-mv99.onrender.com
      groups:
        - android
    triggering:
      events:
        - push
      cancel_previous_builds: true
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web bundle
        script: |
          npm run build
      - name: Sync Capacitor
        script: |
          npx cap sync android
      - name: Build Android
        script: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - tamimiqbalacademic@gmail.com
        notify:
          success: true
          failure: true
